### ISSUE TITLE
Language Selection does not redirect

### ISSUE THREAD

**Issue by DarrellRoberts** [konfuzio-ai/document-validation-ui#349]
When the user is first on the page and they change the language (english in this example), although the ,,/en'' is added to url, the page text remains the same.

![image](https://github.com/konfuzio-ai/document-validation-ui/assets/139546996/d9d6eff2-28f3-4689-b38d-81ddb896d355)

It's only when pressing this pagination component at the bottom does the language switch.

![image](https://github.com/konfuzio-ai/document-validation-ui/assets/139546996/fc5e89b3-ef4a-4ad0-a581-6e11386fee3a)

The URL I used was: https://konfuzio.com/en/document-validation-ui

**Comment by bojidarr** [comment]
Thank you for the feedback. The issue has now been solved.
